version: '3.7'

services:
  telegram-bot-api:
    container_name: telegram-forward-bot-api
    image: aiogram/telegram-bot-api:latest
    env_file: ./.env
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api
    ports:
      - 8082:8081
  
  telegram-bot:
    container_name: telegram-forward-bot
    build: .
    env_file: ./.env
    environment:
      API_HOST: "http://telegram-bot-api:8081"
    volumes:
      - ./db:/app/db
    depends_on:
      - telegram-bot-api

volumes:
  telegram-bot-api-data:

